# Generated by Django 5.1.1 on 2025-03-24 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordsInspectionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_haccp_inspection', models.DateField(blank=True, null=True, verbose_name='Last HACCP Inspection Date')),
                ('last_doh_inspection', models.DateField(blank=True, null=True, verbose_name='Last DOH Inspection Date')),
                ('last_halal_inspection', models.DateField(blank=True, null=True, verbose_name='Last Halal Food Inspection Date')),
                ('failed_food_safety_inspection', models.BooleanField(verbose_name='Has the school ever failed a food safety inspection?')),
                ('halal_certification_visible', models.BooleanField(verbose_name='Is the Halal Certification posted and visible in the kitchen?')),
                ('halal_approved_items_visible', models.BooleanField(verbose_name='Is the latest Halal Approved Items list posted in the kitchen?')),
                ('halal_menu_visible', models.BooleanField(verbose_name='Is the latest Halal Serving Menu list posted in the kitchen?')),
                ('all_halal_documents_posted', models.BooleanField(verbose_name='Are all three documents (Halal Certificate, Approved Items list, and Serving Menu list) posted together and visible?')),
                ('inspection_notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('incident', models.TextField(blank=True, null=True, verbose_name='Incident')),
                ('remedy', models.TextField(blank=True, null=True, verbose_name='Remedy')),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='Conclusion')),
                ('halal_inspection', models.CharField(choices=[('date', 'Date'), ('na', 'N/A')], default='na', max_length=10)),
                ('halal_inspection_date', models.DateField(blank=True, null=True)),
                ('failed_inspection_date', models.DateField(blank=True, null=True)),
                ('record_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records_inspections', to='inspectionApp.schoolinspection', to_field='school_code', verbose_name='School Code (SF Code)')),
            ],
        ),
    ]
