# Generated by Django 5.1.1 on 2025-03-24 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0002_recordsinspectiondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationInspectionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_kitchen_staff', models.PositiveIntegerField(verbose_name='What is the total number of kitchen staff (including Manager)?')),
                ('staff_present', models.PositiveIntegerField(verbose_name='How many staff were present?')),
                ('total_staff', models.PositiveIntegerField(verbose_name='How much total staff?')),
                ('staff_on_time', models.BooleanField(verbose_name='Was the staff on time for the inspection?')),
                ('staff_cooperative', models.BooleanField(verbose_name='Was the staff cooperative?')),
                ('staff_engaged', models.BooleanField(verbose_name='Was the staff engaged?')),
                ('staff_allowed_inspection_time', models.BooleanField(verbose_name='Did the staff allow adequate time for inspection?')),
                ('manager_willingness_halal', models.CharField(choices=[('Not at all', 'Not at all'), ('Slightly negative', 'Slightly negative'), ('Slightly inclined', 'Slightly inclined'), ('Very enthusiastic', 'Very enthusiastic'), ('Neutral', 'Neutral'), ('N/A', 'N/A')], max_length=50, verbose_name='How willing does the Manager feel about integrating Halal in this Kitchen?')),
                ('cook_willingness_halal', models.CharField(choices=[('Not at all', 'Not at all'), ('Slightly negative', 'Slightly negative'), ('Slightly inclined', 'Slightly inclined'), ('Very enthusiastic', 'Very enthusiastic'), ('Neutral', 'Neutral'), ('N/A', 'N/A')], max_length=50, verbose_name='How willing does the Cook feel about integrating Halal in this Kitchen?')),
                ('heavy_duty_willingness_halal', models.CharField(choices=[('Not at all', 'Not at all'), ('Slightly negative', 'Slightly negative'), ('Slightly inclined', 'Slightly inclined'), ('Very enthusiastic', 'Very enthusiastic'), ('Neutral', 'Neutral'), ('N/A', 'N/A')], max_length=50, verbose_name='How willing does the Heavy Duty feel about integrating Halal in this Kitchen?')),
                ('other_staff_willingness_halal', models.CharField(choices=[('Not at all', 'Not at all'), ('Slightly negative', 'Slightly negative'), ('Slightly inclined', 'Slightly inclined'), ('Very enthusiastic', 'Very enthusiastic'), ('Neutral', 'Neutral'), ('N/A', 'N/A')], max_length=50, verbose_name='How willing does the other Staff feel about integrating Halal in this Kitchen?')),
                ('staff_evaluation_notes', models.TextField(blank=True, null=True, verbose_name='Staff Evaluation Notes')),
                ('incident', models.TextField(blank=True, null=True, verbose_name='Incident')),
                ('remedy', models.TextField(blank=True, null=True, verbose_name='Remedy')),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='Conclusion')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_inspections', to='inspectionApp.schoolinspection', to_field='school_code', verbose_name='School Code (SF Code)')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingInspectionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_staff_trained', models.BooleanField(verbose_name='After this visit, have all staff been trained?')),
                ('total_staff_trained', models.PositiveIntegerField(verbose_name='How many total staff are trained?')),
                ('total_staff', models.PositiveIntegerField(verbose_name='How much total staff?')),
                ('manager_trained', models.BooleanField(verbose_name='Has the Manager been trained?')),
                ('cook_trained', models.BooleanField(verbose_name='Has the Cook been trained?')),
                ('halal_training_notes', models.TextField(blank=True, null=True, verbose_name='Halal Training Notes')),
                ('staff_roster_name', models.CharField(max_length=255, verbose_name='Name')),
                ('staff_roster_position', models.CharField(choices=[('Supervisor', 'Supervisor'), ('Manager', 'Manager'), ('Cook', 'Cook'), ('Assistant Cook', 'Assistant Cook'), ('SLH', 'SLH'), ('Heavy Duty', 'Heavy Duty'), ('Substitute', 'Substitute')], max_length=50, verbose_name='Position')),
                ('staff_roster_attendance', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=50, verbose_name='Attendance')),
                ('staff_roster_halal_trained', models.CharField(choices=[('Trained Today', 'Trained Today'), ('Already Trend', 'Already Trend'), ('No', 'No')], max_length=50, verbose_name='Halal Trained')),
                ('staff_roster_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('incident', models.TextField(blank=True, null=True, verbose_name='Incident')),
                ('remedy', models.TextField(blank=True, null=True, verbose_name='Remedy')),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='Conclusion')),
                ('staff_changed', models.TextField(blank=True, help_text='List new employees if staff changed', null=True)),
                ('employees_left', models.CharField(blank=True, help_text='List employees who left', max_length=255, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_inspections', to='inspectionApp.schoolinspection', to_field='school_code', verbose_name='School Code (SF Code)')),
            ],
        ),
    ]
