# Generated by Django 5.1.1 on 2025-03-25 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0003_evaluationinspectiondata_traininginspectiondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaminationRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contamination_risk_assessment', models.CharField(choices=[('None', 'None'), ('Low', 'Low'), ('High', 'High')], max_length=50, verbose_name='What is the contamination potential in this facility? Are there any issues in this particular school that raise any concerns for Halal cross-contamination?')),
                ('school_name', models.CharField(max_length=255, verbose_name='School Name')),
                ('school_address', models.TextField(verbose_name='School Address (Street, State, Zip Code)')),
                ('certification_during_summer', models.BooleanField(verbose_name='Is this Certification during the Summer School period?')),
                ('school_borough', models.CharField(choices=[('Manhattan', 'Manhattan'), ('Bronx', 'Bronx'), ('Queens', 'Queens'), ('Brooklyn', 'Brooklyn'), ('Staten Island', 'Staten Island')], max_length=50, verbose_name='School Borough')),
                ('halal_inspection_evaluation', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Re-Visit', 'Re-Visit')], max_length=50, verbose_name='Halal Inspection Evaluation')),
                ('inspector_name', models.CharField(max_length=255, verbose_name='Inspector Name')),
                ('inspector_email', models.EmailField(max_length=254, verbose_name='Inspector Email')),
                ('inspection_date', models.DateField(verbose_name='Inspection Date')),
                ('inspector_signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name="Inspector's Signature")),
                ('time_signed_in', models.TimeField(verbose_name='Time Signed In')),
                ('time_signed_out', models.TimeField(verbose_name='Time Signed Out')),
                ('clock_out_entry_sent', models.BooleanField(verbose_name='Did you send a picture of your clock out entry in the kitchen log book and send it to your supervisor?')),
                ('incident', models.TextField(blank=True, null=True, verbose_name='Incident')),
                ('remedy', models.TextField(blank=True, null=True, verbose_name='Remedy')),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='Conclusion')),
                ('final_comments', models.TextField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contamination_inspections', to='inspectionApp.schoolinspection', to_field='school_code', verbose_name='School Code (SF Code)')),
            ],
        ),
    ]
