# Generated by Django 5.1.1 on 2025-03-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0004_contaminationrisk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroominspectiondata',
            name='bad_odor_present',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is there any bad odor in the bathroom?'),
        ),
        migrations.AlterField(
            model_name='bathroominspectiondata',
            name='clogged_sinks_or_toilets',
            field=models.BooleanField(blank=True, null=True, verbose_name='Are there any clogged sinks or toilets?'),
        ),
        migrations.AlterField(
            model_name='bathroominspectiondata',
            name='graffiti_present',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is there any graffiti or vandalism in the bathrooms?'),
        ),
        migrations.AlterField(
            model_name='contaminationrisk',
            name='certification_during_summer',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is this Certification during the Summer School period?'),
        ),
        migrations.AlterField(
            model_name='contaminationrisk',
            name='clock_out_entry_sent',
            field=models.BooleanField(blank=True, null=True, verbose_name='Did you send a picture of your clock out entry in the kitchen log book and send it to your supervisor?'),
        ),
        migrations.AlterField(
            model_name='evaluationinspectiondata',
            name='staff_allowed_inspection_time',
            field=models.BooleanField(blank=True, null=True, verbose_name='Did the staff allow adequate time for inspection?'),
        ),
        migrations.AlterField(
            model_name='evaluationinspectiondata',
            name='staff_cooperative',
            field=models.BooleanField(blank=True, null=True, verbose_name='Was the staff cooperative?'),
        ),
        migrations.AlterField(
            model_name='evaluationinspectiondata',
            name='staff_engaged',
            field=models.BooleanField(blank=True, null=True, verbose_name='Was the staff engaged?'),
        ),
        migrations.AlterField(
            model_name='evaluationinspectiondata',
            name='staff_on_time',
            field=models.BooleanField(blank=True, null=True, verbose_name='Was the staff on time for the inspection?'),
        ),
        migrations.AlterField(
            model_name='recordsinspectiondata',
            name='all_halal_documents_posted',
            field=models.BooleanField(blank=True, null=True, verbose_name='Are all three documents (Halal Certificate, Approved Items list, and Serving Menu list) posted together and visible?'),
        ),
        migrations.AlterField(
            model_name='recordsinspectiondata',
            name='failed_food_safety_inspection',
            field=models.BooleanField(blank=True, null=True, verbose_name='Has the school ever failed a food safety inspection?'),
        ),
        migrations.AlterField(
            model_name='recordsinspectiondata',
            name='halal_approved_items_visible',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is the latest Halal Approved Items list posted in the kitchen?'),
        ),
        migrations.AlterField(
            model_name='recordsinspectiondata',
            name='halal_certification_visible',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is the Halal Certification posted and visible in the kitchen?'),
        ),
        migrations.AlterField(
            model_name='recordsinspectiondata',
            name='halal_menu_visible',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is the latest Halal Serving Menu list posted in the kitchen?'),
        ),
        migrations.AlterField(
            model_name='storageinspectiondata',
            name='facility_bad_odors',
            field=models.BooleanField(blank=True, null=True, verbose_name='Does the facility have any bad odors due to poor ventilation?'),
        ),
        migrations.AlterField(
            model_name='storageinspectiondata',
            name='halal_serving_utensils_washed_separately',
            field=models.BooleanField(blank=True, null=True, verbose_name='Are Halal Serving Utensils washed separately?'),
        ),
        migrations.AlterField(
            model_name='storageinspectiondata',
            name='halal_trays_washed_separately',
            field=models.BooleanField(blank=True, null=True, verbose_name='Are Halal Trays washed separately from non-Halal?'),
        ),
        migrations.AlterField(
            model_name='storageinspectiondata',
            name='halal_utensils_trays_halal_sink',
            field=models.BooleanField(blank=True, null=True, verbose_name='Are Halal Utensils/Trays washed in a Halal-Designated sink?'),
        ),
        migrations.AlterField(
            model_name='traininginspectiondata',
            name='all_staff_trained',
            field=models.BooleanField(blank=True, null=True, verbose_name='After this visit, have all staff been trained?'),
        ),
        migrations.AlterField(
            model_name='traininginspectiondata',
            name='cook_trained',
            field=models.BooleanField(blank=True, null=True, verbose_name='Has the Cook been trained?'),
        ),
        migrations.AlterField(
            model_name='traininginspectiondata',
            name='manager_trained',
            field=models.BooleanField(blank=True, null=True, verbose_name='Has the Manager been trained?'),
        ),
    ]
