# Generated by Django 5.1.1 on 2025-03-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0005_alter_bathroominspectiondata_bad_odor_present_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationinspectiondata',
            name='staff_present',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='How many staff were present?'),
        ),
        migrations.AlterField(
            model_name='evaluationinspectiondata',
            name='total_kitchen_staff',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='What is the total number of kitchen staff (including Manager)?'),
        ),
        migrations.AlterField(
            model_name='evaluationinspectiondata',
            name='total_staff',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='How much total staff?'),
        ),
        migrations.AlterField(
            model_name='schoolinspection',
            name='halal_consumption_percentage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Percentage of students consuming Halal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traininginspectiondata',
            name='total_staff',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='How much total staff?'),
        ),
        migrations.AlterField(
            model_name='traininginspectiondata',
            name='total_staff_trained',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='How many total staff are trained?'),
        ),
    ]
