# Generated by Django 5.1.1 on 2025-03-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0006_alter_evaluationinspectiondata_staff_present_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaminationrisk',
            name='inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Inspection Date'),
        ),
        migrations.AlterField(
            model_name='contaminationrisk',
            name='inspector_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Inspector Email'),
        ),
        migrations.AlterField(
            model_name='contaminationrisk',
            name='inspector_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Inspector Name'),
        ),
        migrations.AlterField(
            model_name='contaminationrisk',
            name='time_signed_in',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Signed In'),
        ),
        migrations.AlterField(
            model_name='contaminationrisk',
            name='time_signed_out',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Signed Out'),
        ),
    ]
