# Generated by Django 5.1.1 on 2025-03-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0007_alter_contaminationrisk_inspection_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servinginspectiondata',
            name='halal_positioning',
            field=models.CharField(choices=[('Halal product is clear for consumer to see and choose as an option', 'Halal product is clear for consumer to see and choose as an option'), ('Halal product is not clearly visible for consumers to see or choose', 'Halal product is not clearly visible for consumers to see or choose')], default='none', max_length=255, verbose_name="What about the Halal product's positioning in the serving line? Is the Halal food option clearly visible for the students to see and choose as an equal option against the non-Halal options?"),
        ),
        migrations.AlterField(
            model_name='servinginspectiondata',
            name='halal_product_serving_method',
            field=models.CharField(choices=[('Pre-Plated', 'Pre-Plated'), ('Self-Serve', 'Self-Serve'), ('Served by Staff', 'Served by Staff'), ('Other', 'Other')], default='none', max_length=50, verbose_name='Halal Product Serving Method'),
        ),
        migrations.AlterField(
            model_name='servinginspectiondata',
            name='halal_serving_location',
            field=models.CharField(choices=[('In a Halal designated serving location', 'In a Halal designated serving location'), ('In a Halal/non-Halal mixed serving location', 'In a Halal/non-Halal mixed serving location')], default='none', max_length=255, verbose_name='Where is the Halal product served?'),
        ),
    ]
