# Generated by Django 5.1.1 on 2025-03-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0008_alter_servinginspectiondata_halal_positioning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servinginspectiondata',
            name='halal_positioning',
            field=models.CharField(blank=True, choices=[('Halal product is clear for consumer to see and choose as an option', 'Halal product is clear for consumer to see and choose as an option'), ('Halal product is not clearly visible for consumers to see or choose', 'Halal product is not clearly visible for consumers to see or choose')], max_length=255, null=True, verbose_name="What about the Halal product's positioning in the serving line? Is the Halal food option clearly visible for the students to see and choose as an equal option against the non-Halal options?"),
        ),
        migrations.AlterField(
            model_name='servinginspectiondata',
            name='halal_product_serving_method',
            field=models.CharField(blank=True, choices=[('Pre-Plated', 'Pre-Plated'), ('Self-Serve', 'Self-Serve'), ('Served by Staff', 'Served by Staff'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Halal Product Serving Method'),
        ),
        migrations.AlterField(
            model_name='servinginspectiondata',
            name='halal_serving_location',
            field=models.CharField(blank=True, choices=[('In a Halal designated serving location', 'In a Halal designated serving location'), ('In a Halal/non-Halal mixed serving location', 'In a Halal/non-Halal mixed serving location')], max_length=255, null=True, verbose_name='Where is the Halal product served?'),
        ),
        migrations.AlterField(
            model_name='servinginspectiondata',
            name='halal_sign_type',
            field=models.CharField(blank=True, choices=[('plastic_stand', 'Plastic stand, 8.5" x 11" paper (recommended)'), ('wall_posted', 'Posted on a wall near the serving area'), ('large_sign', 'Large sign taped to glass/metal'), ('small_label', 'Small label taped to glass/metal'), ('none', 'None')], max_length=50, null=True, verbose_name="What type of 'Halal' sign is at the serving area?"),
        ),
        migrations.AlterField(
            model_name='servinginspectiondata',
            name='serving_service_type',
            field=models.CharField(blank=True, choices=[('cafeteria', 'Cafeteria-style (served by servers)'), ('buffet', 'Self-serve buffet style'), ('pre_packaged', 'Self-serve pre-packaged stations'), ('vending_machine', 'Vending machine style'), ('other', 'Other')], max_length=255, null=True, verbose_name="If 'Other', please specify"),
        ),
    ]
