# Generated by Django 5.1.1 on 2025-03-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0009_alter_servinginspectiondata_halal_positioning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinspection',
            name='halal_consumption_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentage of students consuming Halal'),
        ),
        migrations.AlterField(
            model_name='schoolinspection',
            name='inspection_type',
            field=models.CharField(blank=True, choices=[('Recertification', 'Recertification (Annual)'), ('Initial', 'Initial Certification (New School)'), ('Unannounced', 'Unannounced'), ('Remediation', 'Remediation')], max_length=50, null=True, verbose_name='Type of Inspection'),
        ),
        migrations.AlterField(
            model_name='schoolinspection',
            name='inspector_status',
            field=models.CharField(blank=True, choices=[('Certified', 'Certified Inspector'), ('Trainee', 'Trainee')], max_length=50, null=True, verbose_name='Inspector Status'),
        ),
    ]
