# Generated by Django 5.1.1 on 2025-03-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0010_alter_schoolinspection_halal_consumption_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servinginspectiondata',
            name='food_safety_gear_required',
            field=models.BooleanField(default=False, verbose_name='Are staff required to wear food safety gear (e.g., gloves) while serving Halal food?'),
        ),
        migrations.AlterField(
            model_name='servinginspectiondata',
            name='separate_serving_utensils',
            field=models.BooleanField(default=False, verbose_name='Are separate serving utensils used for Halal food?'),
        ),
        migrations.AlterField(
            model_name='servinginspectiondata',
            name='serving_area_properly_lit',
            field=models.BooleanField(default=False, verbose_name='Is the serving area properly lit?'),
        ),
    ]
