# Generated by Django 5.1.1 on 2025-03-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0011_alter_servinginspectiondata_food_safety_gear_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servinginspectiondata',
            name='sign_queue_line',
            field=models.BooleanField(default=False, verbose_name='Clear Halal sign for Queue Line (optional)'),
        ),
        migrations.AlterField(
            model_name='storageinspectiondata',
            name='garbage_emptying_frequency',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Every Shift', 'Every Shift'), ('Weekly', 'Weekly'), ('Other', 'Other')], max_length=50, null=True, verbose_name='How often are the garbage cans emptied?'),
        ),
        migrations.AlterField(
            model_name='storageinspectiondata',
            name='kitchen_cleaning_frequency',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('After Each Shift', 'After Each Shift'), ('Other', 'Other')], max_length=50, null=True, verbose_name='How often is the kitchen cleaned?'),
        ),
        migrations.AlterField(
            model_name='storageinspectiondata',
            name='sanitization_chemicals_used',
            field=models.CharField(blank=True, choices=[('Water only ', 'Water only'), ('Water & Soap', 'Water & Soap'), ('Water & Bleach', 'Water & Bleach'), ('Other', 'Other')], max_length=50, null=True, verbose_name='What chemicals are used to sanitize?'),
        ),
        migrations.AlterField(
            model_name='storageinspectiondata',
            name='utensil_sanitization_method',
            field=models.CharField(blank=True, choices=[('Water & Soap', 'Water & Soap'), ('Water & Bleach', 'Water & Bleach'), ('Other', 'Other')], max_length=50, null=True, verbose_name='If Utensils are jointly used with non-halal products, what is used to wash them?'),
        ),
    ]
