# Generated by Django 5.1.1 on 2025-03-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0012_alter_servinginspectiondata_sign_queue_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroominspectiondata',
            name='adequate_soap',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Other', 'Other')], max_length=10, null=True, verbose_name='Does the bathroom have adequate soap available?'),
        ),
        migrations.AlterField(
            model_name='bathroominspectiondata',
            name='bad_odor_present',
            field=models.BooleanField(default=False, verbose_name='Is there any bad odor in the bathroom?'),
        ),
        migrations.AlterField(
            model_name='bathroominspectiondata',
            name='bathroom_clean',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Pending', 'Pending')], max_length=50, null=True, verbose_name='Are the bathrooms clean?'),
        ),
        migrations.AlterField(
            model_name='bathroominspectiondata',
            name='cleaning_frequency',
            field=models.CharField(blank=True, choices=[('Once a day', 'Once a day'), ('Twice', 'Twice'), ('Other', 'Other')], max_length=10, null=True, verbose_name='How Often is the bathroom cleaned?'),
        ),
        migrations.AlterField(
            model_name='bathroominspectiondata',
            name='clogged_sinks_or_toilets',
            field=models.BooleanField(default=False, verbose_name='Are there any clogged sinks or toilets?'),
        ),
        migrations.AlterField(
            model_name='bathroominspectiondata',
            name='faucets_running',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Other', 'Other')], max_length=10, null=True, verbose_name='Are the Faucets running properly?'),
        ),
        migrations.AlterField(
            model_name='bathroominspectiondata',
            name='graffiti_present',
            field=models.BooleanField(default=False, verbose_name='Is there any graffiti or vandalism in the bathrooms?'),
        ),
        migrations.AlterField(
            model_name='bathroominspectiondata',
            name='hand_dryers_functioning',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Some are not working', 'Some are not working')], max_length=50, null=True, verbose_name='Are the hand dryers functioning properly?'),
        ),
        migrations.AlterField(
            model_name='bathroominspectiondata',
            name='kitchen_staff_bathroom',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Does Kitchen staff have a separate bathroom?'),
        ),
        migrations.AlterField(
            model_name='bathroominspectiondata',
            name='mens_staff_bathroom',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name="Men's Staff Bathroom available?"),
        ),
        migrations.AlterField(
            model_name='bathroominspectiondata',
            name='paper_towels_available',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Partial', 'Partial')], max_length=50, null=True, verbose_name='Are paper towels available in all bathrooms?'),
        ),
        migrations.AlterField(
            model_name='bathroominspectiondata',
            name='remove_apron_signs',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name="Signs for 'Remove Apron' visible?"),
        ),
        migrations.AlterField(
            model_name='bathroominspectiondata',
            name='restroom_cleaner',
            field=models.CharField(blank=True, choices=[('Staff', 'Staff'), ('Janitor', 'Janitor')], max_length=10, null=True, verbose_name='Who cleans the restrooms?'),
        ),
        migrations.AlterField(
            model_name='bathroominspectiondata',
            name='ventilation',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Is the bathroom properly ventilated?'),
        ),
        migrations.AlterField(
            model_name='bathroominspectiondata',
            name='wash_hands_signs',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name="Signs for 'Wash Hands' visible?"),
        ),
        migrations.AlterField(
            model_name='bathroominspectiondata',
            name='womens_staff_bathroom',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name="Women's Staff Bathroom available?"),
        ),
        migrations.AlterField(
            model_name='storageinspectiondata',
            name='halal_pots_separate',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Other', 'Other')], max_length=10, null=True, verbose_name='Are Halal-designated Pots, Pans, Trays washed separately from non-Halal?'),
        ),
    ]
