# Generated by Django 5.1.1 on 2025-03-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0013_alter_bathroominspectiondata_adequate_soap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationinspectiondata',
            name='cook_willingness_halal',
            field=models.CharField(blank=True, choices=[('Not at all', 'Not at all'), ('Slightly negative', 'Slightly negative'), ('Slightly inclined', 'Slightly inclined'), ('Very enthusiastic', 'Very enthusiastic'), ('Neutral', 'Neutral'), ('N/A', 'N/A')], max_length=50, null=True, verbose_name='How willing does the Cook feel about integrating Halal in this Kitchen?'),
        ),
        migrations.AlterField(
            model_name='evaluationinspectiondata',
            name='heavy_duty_willingness_halal',
            field=models.CharField(blank=True, choices=[('Not at all', 'Not at all'), ('Slightly negative', 'Slightly negative'), ('Slightly inclined', 'Slightly inclined'), ('Very enthusiastic', 'Very enthusiastic'), ('Neutral', 'Neutral'), ('N/A', 'N/A')], max_length=50, null=True, verbose_name='How willing does the Heavy Duty feel about integrating Halal in this Kitchen?'),
        ),
        migrations.AlterField(
            model_name='evaluationinspectiondata',
            name='manager_willingness_halal',
            field=models.CharField(blank=True, choices=[('Not at all', 'Not at all'), ('Slightly negative', 'Slightly negative'), ('Slightly inclined', 'Slightly inclined'), ('Very enthusiastic', 'Very enthusiastic'), ('Neutral', 'Neutral'), ('N/A', 'N/A')], max_length=50, null=True, verbose_name='How willing does the Manager feel about integrating Halal in this Kitchen?'),
        ),
        migrations.AlterField(
            model_name='evaluationinspectiondata',
            name='other_staff_willingness_halal',
            field=models.CharField(blank=True, choices=[('Not at all', 'Not at all'), ('Slightly negative', 'Slightly negative'), ('Slightly inclined', 'Slightly inclined'), ('Very enthusiastic', 'Very enthusiastic'), ('Neutral', 'Neutral'), ('N/A', 'N/A')], max_length=50, null=True, verbose_name='How willing does the other Staff feel about integrating Halal in this Kitchen?'),
        ),
        migrations.AlterField(
            model_name='evaluationinspectiondata',
            name='staff_allowed_inspection_time',
            field=models.BooleanField(default=False, verbose_name='Did the staff allow adequate time for inspection?'),
        ),
        migrations.AlterField(
            model_name='evaluationinspectiondata',
            name='staff_engaged',
            field=models.BooleanField(default=False, verbose_name='Was the staff engaged?'),
        ),
        migrations.AlterField(
            model_name='evaluationinspectiondata',
            name='staff_on_time',
            field=models.BooleanField(default=False, verbose_name='Was the staff on time for the inspection?'),
        ),
        migrations.AlterField(
            model_name='recordsinspectiondata',
            name='halal_inspection',
            field=models.CharField(blank=True, choices=[('date', 'Date'), ('na', 'N/A')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='traininginspectiondata',
            name='all_staff_trained',
            field=models.BooleanField(default=False, verbose_name='After this visit, have all staff been trained?'),
        ),
        migrations.AlterField(
            model_name='traininginspectiondata',
            name='cook_trained',
            field=models.BooleanField(default=False, verbose_name='Has the Cook been trained?'),
        ),
        migrations.AlterField(
            model_name='traininginspectiondata',
            name='manager_trained',
            field=models.BooleanField(default=False, verbose_name='Has the Manager been trained?'),
        ),
        migrations.AlterField(
            model_name='traininginspectiondata',
            name='staff_roster_attendance',
            field=models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=50, null=True, verbose_name='Attendance'),
        ),
        migrations.AlterField(
            model_name='traininginspectiondata',
            name='staff_roster_halal_trained',
            field=models.CharField(blank=True, choices=[('Trained Today', 'Trained Today'), ('Already Trend', 'Already Trend'), ('No', 'No')], max_length=50, null=True, verbose_name='Halal Trained'),
        ),
        migrations.AlterField(
            model_name='traininginspectiondata',
            name='staff_roster_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
