# Generated by Django 5.1.1 on 2025-03-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0014_alter_evaluationinspectiondata_cook_willingness_halal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationinspectiondata',
            name='staff_cooperative',
            field=models.BooleanField(default=False, verbose_name='Was the staff cooperative?'),
        ),
        migrations.AlterField(
            model_name='traininginspectiondata',
            name='staff_roster_position',
            field=models.CharField(blank=True, choices=[('Supervisor', 'Supervisor'), ('Manager', 'Manager'), ('Cook', 'Cook'), ('Assistant Cook', 'Assistant Cook'), ('SLH', 'SLH'), ('Heavy Duty', 'Heavy Duty'), ('Substitute', 'Substitute')], max_length=50, null=True, verbose_name='Position'),
        ),
    ]
