# Generated by Django 5.1.1 on 2025-03-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0015_alter_evaluationinspectiondata_staff_cooperative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaminationrisk',
            name='certification_during_summer',
            field=models.BooleanField(default=False, verbose_name='Is this Certification during the Summer School period?'),
        ),
        migrations.AlterField(
            model_name='contaminationrisk',
            name='clock_out_entry_sent',
            field=models.BooleanField(default=False, verbose_name='Did you send a picture of your clock out entry in the kitchen log book and send it to your supervisor?'),
        ),
        migrations.AlterField(
            model_name='contaminationrisk',
            name='contamination_risk_assessment',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Low', 'Low'), ('High', 'High')], max_length=50, null=True, verbose_name='What is the contamination potential in this facility? Are there any issues in this particular school that raise any concerns for Halal cross-contamination?'),
        ),
        migrations.AlterField(
            model_name='contaminationrisk',
            name='halal_inspection_evaluation',
            field=models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Re-Visit', 'Re-Visit')], max_length=50, null=True, verbose_name='Halal Inspection Evaluation'),
        ),
        migrations.AlterField(
            model_name='contaminationrisk',
            name='school_address',
            field=models.TextField(blank=True, null=True, verbose_name='School Address (Street, State, Zip Code)'),
        ),
        migrations.AlterField(
            model_name='contaminationrisk',
            name='school_borough',
            field=models.CharField(blank=True, choices=[('Manhattan', 'Manhattan'), ('Bronx', 'Bronx'), ('Queens', 'Queens'), ('Brooklyn', 'Brooklyn'), ('Staten Island', 'Staten Island')], max_length=50, null=True, verbose_name='School Borough'),
        ),
    ]
