# Generated by Django 5.1.1 on 2025-03-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0016_alter_contaminationrisk_certification_during_summer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinspection',
            name='messaged_supervisor',
            field=models.BooleanField(blank=True, null=True, verbose_name='Did you message your supervisor the time that you officially signed in at the security desk log-in book?'),
        ),
        migrations.AlterField(
            model_name='schoolinspection',
            name='security_asked_id',
            field=models.BooleanField(blank=True, null=True, verbose_name='Did Security ask for your I.D?'),
        ),
        migrations.AlterField(
            model_name='schoolinspection',
            name='security_asked_vaccination',
            field=models.BooleanField(blank=True, null=True, verbose_name='Did Security ask for proof of Vaccination?'),
        ),
        migrations.AlterField(
            model_name='schoolinspection',
            name='signed_in_front_desk',
            field=models.BooleanField(blank=True, null=True, verbose_name='Did you sign in at the front desk with security?'),
        ),
        migrations.AlterField(
            model_name='schoolinspection',
            name='signed_in_kitchen_log',
            field=models.BooleanField(blank=True, null=True, verbose_name="Did you sign into the Kitchen's Visitor Log book?"),
        ),
    ]
