# Generated by Django 5.1.1 on 2025-03-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0017_alter_schoolinspection_messaged_supervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinspection',
            name='other_schools_attached',
            field=models.BooleanField(blank=True, null=True, verbose_name='Are there other schools attached to this building?'),
        ),
    ]
