# Generated by Django 5.1.1 on 2025-03-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0019_userlogdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogdata',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
