# Generated by Django 5.1.1 on 2025-04-02 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0021_hourlysalarycalculation_monthlysalarycalculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlysalarycalculation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='monthlysalarycalculation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
