# Generated by Django 5.1.1 on 2025-04-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0022_hourlysalarycalculation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolinspection',
            name='school_address',
        ),
        migrations.RemoveField(
            model_name='schoolinspection',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='schoolinspection',
            name='state',
        ),
        migrations.RemoveField(
            model_name='schoolinspection',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='schoolinspection',
            name='street_address2',
        ),
        migrations.RemoveField(
            model_name='schoolinspection',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='contaminationrisk',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='contaminationrisk',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Address'),
        ),
        migrations.AddField(
            model_name='contaminationrisk',
            name='street_address2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Address Line 2'),
        ),
        migrations.AddField(
            model_name='contaminationrisk',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='contaminationrisk',
            name='school_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='School Address'),
        ),
        migrations.AlterField(
            model_name='contaminationrisk',
            name='school_name',
            field=models.CharField(max_length=100, verbose_name='School Name'),
        ),
    ]
