# Generated by Django 5.1.1 on 2025-04-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0025_alter_recordsinspectiondata_all_halal_documents_posted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationinspectiondata',
            name='total_staff',
        ),
    ]
