# Generated by Django 5.1.1 on 2025-04-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0026_remove_evaluationinspectiondata_total_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traininginspectiondata',
            name='total_staff',
        ),
        migrations.AlterField(
            model_name='traininginspectiondata',
            name='staff_roster_halal_trained',
            field=models.CharField(blank=True, choices=[('Trained Today', 'Trained Today'), ('Already Trained', 'Already Trained'), ('No', 'No')], max_length=50, null=True, verbose_name='Halal Trained'),
        ),
    ]
