# Generated by Django 5.1.1 on 2025-04-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0028_alter_contaminationrisk_inspector_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bathroominspectiondata',
            name='clogged_sinks_or_toilets',
        ),
        migrations.RemoveField(
            model_name='bathroominspectiondata',
            name='graffiti_present',
        ),
        migrations.RemoveField(
            model_name='bathroominspectiondata',
            name='hand_dryers_functioning',
        ),
        migrations.RemoveField(
            model_name='bathroominspectiondata',
            name='paper_towels_available',
        ),
        migrations.RemoveField(
            model_name='preparationinspectiondata',
            name='machine_cleaned_before_use',
        ),
        migrations.AlterField(
            model_name='traininginspectiondata',
            name='employees_left',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='List employees who left'),
        ),
        migrations.AlterField(
            model_name='traininginspectiondata',
            name='staff_changed',
            field=models.TextField(blank=True, null=True, verbose_name='List new employees if staff changed'),
        ),
    ]
