# Generated by Django 5.1.1 on 2025-04-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0029_remove_bathroominspectiondata_clogged_sinks_or_toilets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traininginspectiondata',
            name='staff_roster_attendance',
        ),
        migrations.RemoveField(
            model_name='traininginspectiondata',
            name='staff_roster_halal_trained',
        ),
        migrations.RemoveField(
            model_name='traininginspectiondata',
            name='staff_roster_name',
        ),
        migrations.RemoveField(
            model_name='traininginspectiondata',
            name='staff_roster_notes',
        ),
        migrations.RemoveField(
            model_name='traininginspectiondata',
            name='staff_roster_position',
        ),
    ]
