# Generated by Django 5.1.1 on 2025-04-05 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0030_remove_traininginspectiondata_staff_roster_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRosterInspectionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_roster_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('staff_roster_position', models.CharField(blank=True, choices=[('Supervisor', 'Supervisor'), ('Manager', 'Manager'), ('Cook', 'Cook'), ('Assistant Cook', 'Assistant Cook'), ('SLH', 'SLH'), ('Heavy Duty', 'Heavy Duty'), ('Substitute', 'Substitute')], max_length=50, null=True, verbose_name='Position')),
                ('staff_roster_attendance', models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=50, null=True, verbose_name='Attendance')),
                ('staff_roster_halal_trained', models.CharField(blank=True, choices=[('Trained Today', 'Trained Today'), ('Already Trained', 'Already Trained'), ('No', 'No')], max_length=50, null=True, verbose_name='Halal Trained')),
                ('staff_roster_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_inspections', to='inspectionApp.schoolinspection', to_field='school_code', verbose_name='School Code (SF Code)')),
            ],
        ),
    ]
