# Generated by Django 5.1.1 on 2025-04-05 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0031_staffrosterinspectiondata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preparationinspectiondata',
            name='machine_designation',
        ),
        migrations.RemoveField(
            model_name='preparationinspectiondata',
            name='machine_serial_number',
        ),
        migrations.RemoveField(
            model_name='preparationinspectiondata',
            name='machine_type',
        ),
        migrations.RemoveField(
            model_name='preparationinspectiondata',
            name='swab_test_result',
        ),
        migrations.CreateModel(
            name='PreparationMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Machine S/N')),
                ('machine_type', models.CharField(blank=True, choices=[('Refrigerator', 'Refrigerator'), ('Freezer', 'Freezer'), ('Oven', 'Oven'), ('Warmer', 'Warmer'), ('Warmer-Oven Hybrid', 'Warmer-Oven Hybrid'), ('Steamer-Oven box', 'Steamer-Oven box'), ('Steamer Table', 'Steamer Table'), ('Milk Chest', 'Milk Chest'), ('Self-Serve merchandiser', 'Self-Serve merchandiser'), ('Hot Food merchandiser', 'Hot Food merchandiser')], max_length=50, null=True, verbose_name='Machine Type')),
                ('machine_designation', models.CharField(blank=True, choices=[('Halal', 'Halal'), ('Mixed-use', 'Mixed-use'), ('N/A', 'N/A')], max_length=50, null=True, verbose_name='Designation')),
                ('swab_test_result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('N/A', 'N/A')], max_length=50, null=True, verbose_name='Swab Test')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepare_machine_inspections', to='inspectionApp.schoolinspection', to_field='school_code', verbose_name='School Code (SF Code)')),
            ],
        ),
    ]
