# Generated by Django 5.1.1 on 2025-04-06 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0032_remove_preparationinspectiondata_machine_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preparationinspectiondata',
            name='utensils_designation',
        ),
        migrations.RemoveField(
            model_name='preparationinspectiondata',
            name='utensils_quantity',
        ),
        migrations.RemoveField(
            model_name='preparationinspectiondata',
            name='utensils_swab_test',
        ),
        migrations.RemoveField(
            model_name='preparationinspectiondata',
            name='utensils_type',
        ),
        migrations.CreateModel(
            name='UtensilsInspectionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utensils_quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity of Utensils')),
                ('utensils_type', models.CharField(blank=True, choices=[('Steamer Pans (deep)', 'Steamer Pans (deep)'), ('Oven/Warmer Pans (Shallow)', 'Oven/Warmer Pans (Shallow)'), ('Serving Tools', 'Serving Tools'), ('Round Pots', 'Round Pots')], max_length=50, null=True, verbose_name='Utensils Type')),
                ('utensils_designation', models.CharField(blank=True, choices=[('Halal', 'Halal'), ('Mixed-use', 'Mixed-use'), ('N/A', 'N/A')], max_length=50, null=True, verbose_name='Utensils Designation')),
                ('utensils_swab_test', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('N/A', 'N/A')], max_length=50, null=True, verbose_name='Utensils Swab Test')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utensils_inspections', to='inspectionApp.schoolinspection', to_field='school_code', verbose_name='School Code (SF Code)')),
            ],
        ),
    ]
