# Generated by Django 5.1.1 on 2025-04-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectionApp', '0033_remove_preparationinspectiondata_utensils_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparationinspectiondata',
            name='countertop_no_pathogens',
            field=models.CharField(blank=True, choices=[('Water', 'Water'), ('Water & Soap', 'Water & Soap'), ('Water & Bleach', 'Water & Bleach'), ('Halal Only', 'Halal Only'), ('Other', 'Other')], max_length=50, null=True, verbose_name='If jointly used with non-halal products, how does the staff ensure no pathogens from non-halal remain?'),
        ),
        migrations.AlterField(
            model_name='preparationinspectiondata',
            name='sink_no_pathogens',
            field=models.CharField(blank=True, choices=[('Water', 'Water'), ('Water & Soap', 'Water & Soap'), ('Water & Bleach', 'Water & Bleach'), ('Halal Only', 'Halal Only'), ('Other', 'Other')], max_length=50, null=True, verbose_name='If jointly used with non-halal products, how does the staff ensure no pathogens from non-halal remain?'),
        ),
    ]
